apiVersion: apps/v1
kind: Deployment
metadata:
  name: bndwhnnt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bndwhnnt
  template:
    metadata:
      labels:
        app: bndwhnnt
    spec:
      containers:
      - image: okteto.dev/ray:latest
        name: bndwhnnt
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "7ad9a000-9645-4739-a6e7-ff3b7d20b6c7"
        - name: Vless_Path
          value: "/vl55thbb5"
        - name: Vmess_UUID
          value: "7ad9a000-9645-4739-a6e7-ff3b7d20b6c7"
        - name: Vmess_Path
          value: "/vm6jjtfvb66"
        - name: Share_Path
          value: "/v2link"
